[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] } #to parse jason # derive  feature enable to acess macros
serde_json = "1.0" #allow to fetch json from api
